apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: adaptive-concurrency-filter
spec:
  workloadSelector:
    labels:
      app: nginx # change to your app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '^1\.8.*'
      listener:
        name: virtualInbound
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          config:
            name: adaptive_concurrency_filter
            rootId: lmarszal.http.adaptive_concurrency_filter
            vmConfig:
              vmId: adaptive_concurrency_filter
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  filename: /var/local/lib/wasm-filters/adaptive_concurrency_filter.wasm
              allow_precompiled: true
            configuration: |
              {
                "limit": 5,
                "window_size": 5000,
                "prometheus_cluster_name": "outbound|9090||prometheus.istio-system.svc.cluster.local",
                "prometheus_limit_query": "envoy_http_adaptive_concurrency_filter_requests_limit{pod_name=~\"nginx-.*\"}",
                "prometheus_longrtt_query": "envoy_http_adaptive_concurrency_filter_requests_long_rtt{pod_name=~\"nginx-.*\"}"
              }
        name: envoy.filters.http.wasm
